export enum ActionType {
    SET_ORDER_ADDRESS = "SET_ORDER_ADDRESS",
    REMOVE_ORDER_ADDRESS = "REMOVE_ORDER_ADDRESS",
    SET_ORDER_AMOUNT = "SET_ORDER_AMOUNT",
    SET_USER_ALL_ORDERS = "SET_USER_ALL_ORDERS",
    ADD_NEW_USER_ORDERS = "ADD_NEW_USER_ORDERS",
    CLEAR_USER_ALL_ORDERS = "CLEAR_USER_ALL_ORDERS",
  }